### ISSUE TITLE
EPIC: CCTP should be fully implemented

### ISSUE THREAD

**Issue by bd21** [strangelove-ventures/noble#118]
```gherkin
Scenario: Strangelove will implement a CCTP Relayer that enables the following use case:
  When a User initiates token burn on ETH using dYdX App
  Then IBC forwarding information is (optionally) included in the message metadata
  When ~13 minutes elapse for burn finality on ETH
  Then Strangelove CCTP Relayer observes burn on ETH
  And requests Attestations from Circle API 
  And manages retry handling for block observation errors and attestation request errors
  When Circle API proves burn and issues attestation
  Then Strangelove CCTP Relayer broadcasts tx to Noble chain with attestations (with retry handling on broadcast errors)
  And Noble chain validates attestations, performs mint, then initiates IBC forward if specified
```

---

Design [here](https://notion.so/strangeloveventures/Noble-CCTP-rev-3-8b3064b246914348a506abb8817380ad#c8912a64e43c4d0fb27b370c6e52bcc4)

```[tasklist]
### Tasks
- [ ] https://github.com/strangelove-ventures/noble/issues/221
- [ ] https://github.com/strangelove-ventures/noble/issues/219
- [ ] https://github.com/strangelove-ventures/noble/issues/220
- [ ] https://github.com/strangelove-ventures/noble/issues/224
- [ ] https://github.com/strangelove-ventures/noble/issues/222
- [ ] https://github.com/strangelove-ventures/noble/issues/223
- [ ] https://github.com/strangelove-ventures/noble/issues/218
- [ ] https://github.com/strangelove-ventures/noble/issues/120
- [ ] https://github.com/strangelove-ventures/noble/issues/230
```

**Comment by bd21** [comment]
Current threads-
- Working through the CCTP Module PR by PR with Circle.  Walkthrough with Halborn on Tuesday next week.
- Router module is out for audit.
- We have a duct-taped version of both modules on testnet with a working interchain test for mint+forward.  This should be good enough for DYDX to integrate

@jonathanpberger
