### ISSUE TITLE
EPIC: Build CCTP Router module

### ISSUE THREAD

**Issue by jonathanpberger** [strangelove-ventures/noble#219]
```[tasklist]
### Tasks
- [x] 10 - Router protos, scaffolding
- [x] 11 - Business logic + tests (~6 files)
- [x] https://github.com/strangelove-ventures/noble-router-audit-release
```
